//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID { get; set; }
        public int AddressID { get; set; }
        public int ResidentID { get; set; }
        public string PhoneNumber { get; set; }
        public string ProblemDescription { get; set; }
        public int EmployeeID { get; set; }
        public int ApplicationStatusID { get; set; }
        public Nullable<System.DateTime> DateOfCompletion { get; set; }
        public int FlatNumber { get; set; }
    
        public virtual AllAddresses AllAddresses { get; set; }
        public virtual ApplicationStatuses ApplicationStatuses { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Residents Residents { get; set; }
    }
}
