//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Emelyanenko_HouseManagementEntities : DbContext
    {
        public Emelyanenko_HouseManagementEntities()
            : base("name=Emelyanenko_HouseManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private static Emelyanenko_HouseManagementEntities instance;
        public static Emelyanenko_HouseManagementEntities GetInstance()
        {
            if (instance == null)
            {
                instance = new Emelyanenko_HouseManagementEntities();
            }
            return instance;
        }

        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Жильцы> Жильцы { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<ОтчетПоОплате> ОтчетПоОплате { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<СписокЖилогоФонда> СписокЖилогоФонда { get; set; }
        public virtual DbSet<СписокЗадолженностей> СписокЗадолженностей { get; set; }
        public virtual DbSet<СтатусыЗаявок> СтатусыЗаявок { get; set; }
    }
}
