//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Emelyanenko_HouseManagementEntities : DbContext
    {
        public Emelyanenko_HouseManagementEntities()
            : base("name=Emelyanenko_HouseManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private static Emelyanenko_HouseManagementEntities instance;
        public static Emelyanenko_HouseManagementEntities GetInstance()
        {
            if (instance == null)
            {
                instance = new Emelyanenko_HouseManagementEntities();
            }
            return instance;
        }

        public virtual DbSet<AllAddresses> AllAddresses { get; set; }
        public virtual DbSet<ApplicationStatuses> ApplicationStatuses { get; set; }
        public virtual DbSet<DebtsList> DebtsList { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<PaymentReport> PaymentReport { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Residents> Residents { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
    }
}
