//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReport
    {
        public int ID { get; set; }
        public int OwnerID { get; set; }
        public int AddressID { get; set; }
        public int FlatNumber { get; set; }
        public string Period { get; set; }
        public decimal Credited { get; set; }
        public Nullable<decimal> Paid { get; set; }
    
        public virtual AllAddresses AllAddresses { get; set; }
        public virtual Residents Residents { get; set; }
    }
}
