//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int ID { get; set; }
        public string Адрес { get; set; }
        public int ID_Жильца { get; set; }
        public string Телефон { get; set; }
        public string Описание_Проблемы { get; set; }
        public int Ответственный_Исполнитель { get; set; }
        public int СтатусЗаявки { get; set; }
    
        public virtual Жильцы Жильцы { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual СтатусыЗаявок СтатусыЗаявок { get; set; }
    }
}
