//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокЗадолженностей
    {
        public int ID { get; set; }
        public int ID_Адреса { get; set; }
        public int Квартира { get; set; }
        public int ID_Владельца { get; set; }
        public string Телефон { get; set; }
        public decimal Вода { get; set; }
        public Nullable<decimal> Электроэнергия { get; set; }
    
        public virtual Жильцы Жильцы { get; set; }
        public virtual СписокЖилогоФонда СписокЖилогоФонда { get; set; }
    }
}
