//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокЖилогоФонда
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public СписокЖилогоФонда()
        {
            this.ОтчетПоОплате = new HashSet<ОтчетПоОплате>();
            this.СписокЗадолженностей = new HashSet<СписокЗадолженностей>();
            this.Заявки = new HashSet<Заявки>();
        }
    
        public int ID { get; set; }
        public string Адрес { get; set; }
        public System.DateTime Начало_управления { get; set; }
        public int Этажей { get; set; }
        public Nullable<int> Квартир { get; set; }
        public int Год { get; set; }
        public double Площадь_м2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтчетПоОплате> ОтчетПоОплате { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокЗадолженностей> СписокЗадолженностей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки { get; set; }
    }
}
